blogapp/urls.py
from django.urls import path
from . import views


app_name = 'blogapp'
urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blogapp.urls')),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models

class Inside(models.Model):

    title = models.CharField(max_length = 100)
    text = models.TextField()
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

# Create your models here.

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blogapp/views.py
from django.shortcuts import render
from .models import Inside

def all_blogs(request):

    inside = Inside.objects.order_by('-date')
    return render(request, 'blogapp/all_blogs.html',{'insides':inside})
# Create your views here.

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    project = Project.objects.all()
    return render(request, 'portfolio/home.html',{'projects':project})

blogapp/templates/blogapp/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}



            <h1>My Reviews</h1>

            <h3>Deekshith has {{ insides.count }} review{{ insides.count|pluralize }}</h3>

            {% for inside in insides %}

            <h2>{{ inside.title }}</h2>
            <h5>{{ inside.date }}</h5>
            <p>{{ inside.text }}</p>


            {% endfor %}

  {% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>

{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static "portfolio/DKLOGO.png" %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <title>Deekshith Hari</title>
  </head>
  <body>
            <nav class="navbar navbar-expand-md navbar-light">
            <div class="container">
              <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static "portfolio/DKLOGO.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
                <span id="DK">Deekshith Hari</span>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse text-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="https://github.com/deekhari00716">
                        <img src="{% static "portfolio/github.png" %}" width="24" height="24" style="margin:12px">
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="https://www.linkedin.com/feed/" target="_blank" style="margin:12px">
                        <img src="{% static "portfolio/linkdin.png" %}" width="24" height="24">
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="https://discordapp.com/channels/@me" target="_blank" style="margin:12px">
                        <img src="{% static "portfolio/code.png" %}" width="24" height="24">
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="https://www.instagram.com/deekshi_mambally/" target="_blank" style="margin:12px">
                          <img src="{% static "portfolio/instagram.png" %}" width="24" height="24">
                    </a>
                  </li>
                  <li>
                    <a role="button" href="{% url 'blogapp:all_blogs' %}" class="btn btn-primary" style="margin:12px">Reviews</a>
                  </li>
                  <li>
                    <a role="button" href="https://www.worldometers.info/coronavirus/" class="btn btn-danger" style="margin:12px">Covid19</a>
                  </li>

                </ul>
              </div>
            </div>
          </nav>

            <div class="container">
                {% block content %}{% endblock %}
            </div>




            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}





            {% load static %}
            <!-- <a href="{% url 'blogapp:all_blogs' %}">Hobbies</a> -->
            <div class="row justify-content-center my-3">
              <div class="col-5">
                  <a href="http://127.0.0.1:8000/static/portfolio/50165432_2331561090187377_5777508780157698048_o.jpg">
                    <img src="{% static 'portfolio/50165432_2331561090187377_5777508780157698048_o.jpg' %}" width="400" height="400" class="img-fluid">
                  </a>
              </div>
            </div>
            <div class="row justify-content-center mb-3">
              <div class="col-md-9 text-center">
                <h1 id="hometext" class="font-weight-bold">Deekshith Hari is a self-taught programmer and lives in Bangalore,India 😊</h1>
              </div>
            </div>
            <h2 class="mt-5">Portfolio</h2>
            <hr>
            <div class="row">
            {% for project in projects %}
            <div class="col-lg-4 col-md-6">

              {% if project.url %}
              <a href="{{ project.url }}">
                <img src="{{ project.image.url }}" class="img-fluid mb-2">
              </a>
              {% else %}

              <img src="{{ project.image.url }}" class="img-fluid mb-2">
              {% endif %}
              <h3>{{ project.title }}</h3>
              <p>{{ project.description }}</p>

            </div>
            {% endfor %}
          </div>

          {% endblock %}